# Autogenerated wrapper script for zfp_jll for aarch64-apple-darwin
export libzfp

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("zfp")
JLLWrappers.@declare_library_product(libzfp, "@rpath/libzfp.1.dylib")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libzfp,
        "lib/libzfp.1.0.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
