# Autogenerated wrapper script for zfp_jll for armv7l-linux-musleabihf
export libzfp

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("zfp")
JLLWrappers.@declare_library_product(libzfp, "libzfp.so.1")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libzfp,
        "lib/libzfp.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
