# Autogenerated wrapper script for zfp_jll for x86_64-w64-mingw32
export libzfp

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("zfp")
JLLWrappers.@declare_library_product(libzfp, "libzfp.dll")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libzfp,
        "bin\\libzfp.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
